# Use an official Python runtime as a parent image
FROM python:3.11.8-slim-bookworm

# Set the working directory in the container to /app
WORKDIR /app

# Add the current directory contents into the container at /app
ADD . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Set environment variable
ENV FLASK_APP=cod-article-7days.py

# Run the application
CMD ["gunicorn", "-b", "0.0.0.0:5000", "cod-article-7days:app"]