kind: Pod
apiVersion: v1
metadata:
  name: blog-sum-blog-backend
spec:
  containers:
    - name: blog-sum-blog-backend
      image: vidbot.azurecr.io/blog-sum-blog-backend:latest
      volumeMounts:
      - name: secrets-store01-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true
  volumes:
    - name: secrets-store01-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-kvname-user-msi"