apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"        
    userAssignedIdentityID: b7d69f02-c616-4e6a-a63e-5fa50f54e805  
    keyvaultName: ask-keys-jml       
    cloudName: ""               
    objects:  |
      array:
        - |
          objectName: AzureOpenaiAPI
          objectType: secret              
          objectVersion: ""              
        - |
          objectName: AzureOpenaiEnpoint
          objectType: secret
          objectVersion: ""
    tenantId: a66c126e-b413-409f-a3dc-9b0f96cced34              